watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"

bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: True 
      acrylic: false 
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["active_window"]
      center: ["clock"]
      right: ["media","libre_gpu","wifi","bluetooth","volume","power_menu"]
widgets:
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "<span>\uf001</span> {title}"
        label_alt: "<span>\uf001</span> {artist}"
        hide_empty: true
        max_field_size:
          label: 20
          label_alt: 20
        show_thumbnail: false
        controls_only: false
        controls_left: true
        thumbnail_alpha: 0
        thumbnail_padding: 0
        thumbnail_corner_radius: 0
        icons:
          prev_track: "\ue627"
          next_track: "\ue628"
          play: "\uf5b0"
          pause: "\uf8ae"
  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%H:%M}"
        label_alt: "{%d de %b %H:%M}"
        timezones: [] #Looking up time zone info from registry
        tooltip: false
        locale: "es-ES"
        update_interval: 60000
  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span>"
        label_alt: "{volume}"
        volume_icons:
          - "\ueee8"  # Icon for muted
          - "\uf026"  # Icon for 0-10% volume
          - "\uf027"  # Icon for 11-30% volume
          - "\uf027"  # Icon for 31-60% volume
          - "\uf028"  # Icon for 61-100% volume
        callbacks:
          on_right: "exec cmd.exe /c start ms-settings:sound"
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{device_name}"
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: False
        blur: False
        blur_background: True
        animation_duration: 100 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          signout: ["\udb80\udf43","Cerrar Sesi√≥n"]
          shutdown: ["\uf011","Apagar"]
          restart: ["\uead2","Reiniciar"]
          hibernate: ["\uf28e","Hibernar"]
          cancel: ["\udb81\udf3a","Cancelar"]
  active_window:
      type: "yasb.active_window.ActiveWindowWidget"
      options:
        label: "{win[title]}"
        label_alt: "{win[process][name]} hwnd={win[hwnd]}"
        label_no_window: ""
        label_icon: True
        label_icon_size: 10
        max_length: 30
        max_length_ellipsis: "..."
        monitor_exclusive: true
  battery:
      type: "yasb.battery.BatteryWidget"
      options:
        label: "<span>{icon}</span>{percent}%"
        label_alt: "{icon} {percent}% | time: {time_remaining}"
        charging_options:
          icon_format: "{charging_icon}"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec wifi_settings"
        on_right: "exec cmd.exe /c start ms-settings:network"
  libre_gpu:
    type: "yasb.libre_monitor.LibreHardwareMonitorWidget"
    options:
      label: "{info[value]}"
      label_alt: "CPU"
      sensor_id: "/intelcpu/0/temperature/0"
      update_interval: 1000
      precision: 0
      histogram_num_columns: 10
      class_name: "libre-monitor-widget"

      history_size: 60
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+

      # histogram_fixed_min: 0.0
      # histogram_fixed_max: 100.0

      server_host: "localhost"
      server_port: 8085

      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
